FROM python:3.11

WORKDIR /app

COPY api/requirements.txt /app/requirements.txt
# RUN pip install --no-cache-dir -r /app/requirements.txt
RUN pip install --no-cache-dir \
    --trusted-host pypi.org \
    --trusted-host files.pythonhosted.org \
    -r /app/requirements.txt

COPY api/ /app/

EXPOSE 5000

CMD ["python", "app.py"]